# Generated by Django 5.0 on 2023-12-08 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_variant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
