# Generated by Django 5.0 on 2023-12-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_delete_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price1',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_discount',
            new_name='total_price',
        ),
    ]
