# Generated by Django 5.0 on 2024-01-18 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_commentproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentproduct',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='product.commentproduct'),
        ),
    ]
