# Generated by Django 5.0 on 2024-07-08 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_price',
        ),
    ]
