# Generated by Django 5.0 on 2023-12-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=350)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=70)),
                ('subject', models.CharField(max_length=350)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contact us',
                'ordering': ['-created'],
            },
        ),
    ]
