# Generated by Django 5.0 on 2023-12-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=300, verbose_name='site name')),
                ('site_url', models.URLField(blank=True, null=True, verbose_name='url')),
                ('logo_site', models.ImageField(blank=True, null=True, upload_to='uploads/logo_site', verbose_name='logo site')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitterX', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('pinterest', models.URLField(blank=True, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('number_customer_support', models.CharField(max_length=30, verbose_name='number customer support')),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(max_length=700)),
                ('copy_right', models.CharField(max_length=500)),
                ('about_us', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'setting',
                'verbose_name_plural': 'settings site',
            },
        ),
    ]
